### ISSUE TITLE
Code Release?

### ISSUE THREAD

**Issue by AmanKishore** [Picsart-AI-Research/Text2Video-Zero#1]
Edge guidance is cool, how long of a video can I create?

**Comment by JiauZhang** [comment]
> Edge guidance is cool, how long of a video can I create?

This paper is so interesting, so I'm doing it myself. --> https://github.com/JiauZhang/Text2Video-Zero

**Comment by rob-hen** [comment]
We provide the option to process a video in chunks. Using that you can process long videos while the VRAM usage is constant for each chunk.

**Comment by AmanKishore** [comment]
Thank you for the code!
