### ISSUE TITLE
Thanks for the project ❤, I made a Colab. I hope you like it.

### ISSUE THREAD

**Issue by camenduru** [Picsart-AI-Research/Text2Video-Zero#13]
It's working with a free Colab T4 GPU 🥳 Please try it 🐣
https://github.com/camenduru/text2video-zero-colab

**Comment by dwaynefoong** [comment]
thank you for the contribution

**Comment by kolabearafk** [comment]
Thank you for the Colab version. But why aren't the results from this repo and the results from the colab not matching? The examples from the Colab version seem to be lacking the temporal consistency?  Please see below for the example with the prompt "a horse is galloping on a street".

https://user-images.githubusercontent.com/125360715/228503864-b4717b61-8259-418f-8434-0b0b20c5642e.mp4

**Comment by camenduru** [comment]
seeds are random oops, Hi @kolabearafk 👋 @MaayanBogin 👋 @toughyear 👋 thanks for the info ❤  maybe it's fixed now, please try it again.

**Comment by toughyear** [comment]
@camenduru trying. Will update.

**Comment by camenduru** [comment]
🔥 thanks @toughyear ❤ please join our discord server https://discord.gg/k5BwmmvJJU maybe we can make some little improvements together

**Comment by camenduru** [comment]
![image (6)](https://user-images.githubusercontent.com/54370274/228672175-4e2032bd-2c54-4b3e-8252-3de5a88c6275.gif)

**Comment by camenduru** [comment]
with custom model https://huggingface.co/plasmo/woolitize-768sd1-5
![image (7)](https://user-images.githubusercontent.com/54370274/228675411-a774eb6b-dc95-4e4c-b499-69617cac2969.gif)

**Comment by toughyear** [comment]
joined.
