### ISSUE TITLE
My thoughts and fixes to get this running

### ISSUE THREAD

**Issue by chrisbward** [Picsart-AI-Research/Text2Video-Zero#19]
Right, here are the REAL instructions for using this repo;

```
python3.9 -m venv ./.venv
source ./.venv/bin/activate
pip install --upgrade pip
pip install wheel
```
make the following change in requirements.txt;
```
-opencv-contrib-python==4.3.0.36
+opencv-contrib-python==4.4.0.46
```

install requirements;
```
pip install -r requirements.txt
```

disable the app from sharing itself and your machine to the world, without your permission or knowledge of doing so;
ARE YOU BEING SERIOUS?!?

```
-_,_,link = demo.queue(api_open=False).launch(file_directories=['temporal'], share=True)
+_,_,link = demo.queue(api_open=False).launch(file_directories=['temporal'], share=False)
```

then, it should launch with `python app.py`, enter a prompt and wait for the models to download..... somewhere?!?!

inferrence begins and then you end up with something that resembles 8 SD images stitched together with ffmpeg, a gif basically.

![7gb9bb](https://user-images.githubusercontent.com/888374/228620967-f33ae452-9569-4bee-abc9-06d83c80da5a.png)

**Comment by rob-hen** [comment]
When the `chunk_size` stays the same, it will process the sequence sequentially. The first `chunk_size` frames, then the next `chunk_size` frames and so on. Thus, there should not be an exponential growth.

**Comment by rob-hen** [comment]
HI @chrisbward,  

thank you for detailed descriptions and concerns. We have update the code so that by default, no public link is created.
We have also elaborated more on the installation and updated the `requirements.txt`.

**Comment by Cubey42** [comment]
will the git repo get the hf update so we can use other models in t2v?
