### ISSUE TITLE
torch.cuda.OutOfMemoryError

### ISSUE THREAD

**Issue by it-coder** [Picsart-AI-Research/Text2Video-Zero#24]
Thank you very much for your release. What are the graphics card configuration requirements? 
torch.cuda.OutOfMemoryError appears when my RTX3060 runs the example

**Comment by rob-hen** [comment]
In the minimal setup, 12 GB VRAM are necessary. We will soon further decrease the required memory.

**Comment by rob-hen** [comment]
Our latest code can be tested with less than 7GB VRAM.

**Comment by it-coder** [comment]
Thank you very much. I'll try again

**Comment by sakshamjindal** [comment]
It does not yet work with 12 GB. What are the settings that enable it ?
