### ISSUE TITLE
RuntimeError: Device type CUDA is not supported for torch.Generator() api.

### ISSUE THREAD

**Issue by Cubey42** [Picsart-AI-Research/Text2Video-Zero#25]
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ H:\AI video\t2v0\Text2Video-Zero\app.py:14 in <module>                                           │
│                                                                                                  │
│   11 import os                                                                                   │
│   12                                                                                             │
│   13 on_huggingspace = os.environ.get("SPACE_AUTHOR_NAME") == "PAIR"                             │
│ ❱ 14 model = Model(device='cuda', dtype=torch.float16)                                           │
│   15 parser = argparse.ArgumentParser()                                                          │
│   16 parser.add_argument('--public_access', action='store_true',                                 │
│   17 │   │   │   │   │   help="if enabled, the app can be access from a public url", default=    │
│                                                                                                  │
│ H:\AI video\t2v0\Text2Video-Zero\model.py:27 in __init__                                         │
│                                                                                                  │
│    24 │   def __init__(self, device, dtype, **kwargs):                                           │
│    25 │   │   self.device = device                                                               │
│    26 │   │   self.dtype = dtype                                                                 │
│ ❱  27 │   │   self.generator = torch.Generator(device=device)                                    │
│    28 │   │   self.pipe_dict = {                                                                 │
│    29 │   │   │   ModelType.Pix2Pix_Video: StableDiffusionInstructPix2PixPipeline,               │
│    30 │   │   │   ModelType.Text2Video: TextToVideoPipeline,                                     │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: Device type CUDA is not supported for torch.Generator() api.

worked fine before, not sure whats changed, tried reinstalling torch but didn't help

**Comment by Cubey42** [comment]
tried a new env, still no change.

**Comment by rob-hen** [comment]
In order to find the cause of this error, can you show all packages installed (via  `pip freeze`) and the CUDA version installed ?

**Comment by Cubey42** [comment]
absl-py==1.4.0
accelerate==0.16.0
addict==2.4.0
aiofiles==23.1.0
aiohttp==3.8.4
aiosignal==1.3.1
albumentations==1.3.0
altair==4.2.2
antlr4-python3-runtime==4.9.3
anyio==3.6.2
async-timeout==4.0.2
attrs==22.2.0
basicsr==1.4.2
beautifulsoup4==4.12.0
braceexpand==0.1.7
bs4==0.0.1
cachetools==5.3.0
certifi==2022.12.7
charset-normalizer==3.1.0
click==8.1.3
colorama==0.4.6
coloredlogs==15.0.1
contourpy==1.0.7
cycler==0.11.0
decorator==4.4.2
decord==0.6.0
diffusers==0.14.0
einops==0.6.0
entrypoints==0.4
fastapi==0.95.0
ffmpy==0.3.0
filelock==3.10.7
flatbuffers==23.3.3
fonttools==4.39.3
frozenlist==1.3.3
fsspec==2023.3.0
ftfy==6.1.1
future==0.18.3
google-auth==2.17.0
google-auth-oauthlib==0.4.6
gradio==3.23.0
grpcio==1.53.0
h11==0.14.0
httpcore==0.16.3
httpx==0.23.3
huggingface-hub==0.13.3
humanfriendly==10.0
idna==3.4
imageio==2.9.0
imageio-ffmpeg==0.4.2
importlib-metadata==6.1.0
invisible-watermark==0.1.5
Jinja2==3.1.2
joblib==1.2.0
jsonschema==4.17.3
kiwisolver==1.4.4
kornia==0.6.0
linkify-it-py==2.0.0
lmdb==1.4.0
Markdown==3.4.3
markdown-it-py==2.2.0
MarkupSafe==2.1.2
matplotlib==3.7.1
mdit-py-plugins==0.3.3
mdurl==0.1.2
moviepy==1.0.3
mpmath==1.3.0
multidict==6.0.4
networkx==3.0
numpy==1.24.1
oauthlib==3.2.2
omegaconf==2.3.0
onnx==1.13.1
onnxruntime==1.14.1
open-clip-torch==2.16.0
opencv-contrib-python==4.7.0.72
opencv-python==4.7.0.72
opencv-python-headless==4.7.0.72
orjson==3.8.9
packaging==23.0
pandas==1.5.3
Pillow==9.4.0
prettytable==3.6.0
proglog==0.1.10
protobuf==3.20.3
psutil==5.9.4
pyasn1==0.4.8
pyasn1-modules==0.2.8
pydantic==1.10.7
pyDeprecate==0.3.1
pydub==0.25.1
pyparsing==3.0.9
pyreadline3==3.4.1
pyrsistent==0.19.3
python-dateutil==2.8.2
python-multipart==0.0.6
pytorch-lightning==1.5.0
pytz==2023.3
PyWavelets==1.4.1
PyYAML==6.0
qudida==0.0.4
regex==2023.3.23
requests==2.28.2
requests-oauthlib==1.3.1
rfc3986==1.5.0
rsa==4.9
safetensors==0.2.7
scikit-image==0.19.3
scikit-learn==1.2.2
scipy==1.10.1
semantic-version==2.10.0
sentencepiece==0.1.97
six==1.16.0
sniffio==1.3.0
soupsieve==2.4
starlette==0.26.1
sympy==1.11.1
tb-nightly==2.13.0a20230317
tensorboard==2.12.0
tensorboard-data-server==0.7.0
tensorboard-plugin-wit==1.8.1
tensorboardX==2.6
test-tube==0.7.5
threadpoolctl==3.1.0
tifffile==2023.3.21
timm==0.6.12
tokenizers==0.13.2
toolz==0.12.0
torch==1.13.1
torchmetrics==0.6.0
torchvision==0.14.1
tqdm==4.64.1
transformers==4.26.0
typing_extensions==4.5.0
uc-micro-py==1.0.1
urllib3==1.26.15
uvicorn==0.21.1
wcwidth==0.2.6
webdataset==0.2.5
websockets==10.4
Werkzeug==2.2.3
yapf==0.32.0
yarl==1.8.2
zipp==3.15.0

CUDA 11.8.89

**Comment by rob-hen** [comment]
PyTorch 1.13.1 needs CUDA >= 11.6.

You can either try to install a newer CUDA version. It might also work with an older PyTorch version that supports your currently installed CUDA version, see https://pytorch.org/get-started/previous-versions/ .

**Comment by Cubey42** [comment]
CUDA ia 11.8, so not >= 11.6?

**Comment by rob-hen** [comment]
According to https://pytorch.org/get-started/previous-versions/ 1.13.1 works with CUDA 11.6 and CUDA 11.7.
Could you try one of these versions?

**Comment by Cubey42** [comment]
I downloaded 11.7 and it still didn't work, same error

(.venv) (base) PS H:\AI video\t2v0\Text2Video-Zero> python app.py
H:\AI video\t2v0\Text2Video-Zero\annotator\openpose\body.py:5: DeprecationWarning: Please use `gaussian_filter` from the `scipy.ndimage` namespace, the `scipy.ndimage.filters` namespace is deprecated.
  from scipy.ndimage.filters import gaussian_filter
H:\AI video\t2v0\Text2Video-Zero\annotator\openpose\hand.py:6: DeprecationWarning: Please use `gaussian_filter` from the `scipy.ndimage` namespace, the `scipy.ndimage.filters` namespace is deprecated.
  from scipy.ndimage.filters import gaussian_filter
H:\AI video\t2v0\Text2Video-Zero\.venv\lib\site-packages\skimage\util\dtype.py:27: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  np.bool8: (False, True),
Traceback (most recent call last):
  File "H:\AI video\t2v0\Text2Video-Zero\app.py", line 14, in <module>
    model = Model(device='cuda', dtype=torch.float16)
  File "H:\AI video\t2v0\Text2Video-Zero\model.py", line 27, in __init__
    self.generator = torch.Generator(device=device)
RuntimeError: Device type CUDA is not supported for torch.Generator() api.
(.venv) (base) PS H:\AI video\t2v0\Text2Video-Zero> nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Tue_May__3_19:00:59_Pacific_Daylight_Time_2022
Cuda compilation tools, release 11.7, V11.7.64
Build cuda_11.7.r11.7/compiler.31294372_0

**Comment by Cubey42** [comment]
it worked before this latest pull

**Comment by rob-hen** [comment]
I notice that you have two environments loaded "(.venv)" and "(base)". Can you make sure you are in the right environment, with PyTorch correctly loaded for the CUDA version installed.

**Comment by Cubey42** [comment]
Sorry, it was my other environment tried to test, heres in my conda env:
(T2VZeroNew) H:\AI video\t2v0\Text2Video-Zero>python app.py
H:\AI video\t2v0\Text2Video-Zero\annotator\openpose\body.py:5: DeprecationWarning: Please use `gaussian_filter` from the `scipy.ndimage` namespace, the `scipy.ndimage.filters` namespace is deprecated.
  from scipy.ndimage.filters import gaussian_filter
H:\AI video\t2v0\Text2Video-Zero\annotator\openpose\hand.py:6: DeprecationWarning: Please use `gaussian_filter` from the `scipy.ndimage` namespace, the `scipy.ndimage.filters` namespace is deprecated.
  from scipy.ndimage.filters import gaussian_filter
C:\Users\Lucas\.conda\envs\T2VZeroNew\lib\site-packages\skimage\util\dtype.py:27: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  np.bool8: (False, True),
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ H:\AI video\t2v0\Text2Video-Zero\app.py:14 in <module>                                           │
│                                                                                                  │
│   11 import os                                                                                   │
│   12                                                                                             │
│   13 on_huggingspace = os.environ.get("SPACE_AUTHOR_NAME") == "PAIR"                             │
│ ❱ 14 model = Model(device='cuda', dtype=torch.float16)                                           │
│   15 parser = argparse.ArgumentParser()                                                          │
│   16 parser.add_argument('--public_access', action='store_true',                                 │
│   17 │   │   │   │   │   help="if enabled, the app can be access from a public url", default=    │
│                                                                                                  │
│ H:\AI video\t2v0\Text2Video-Zero\model.py:27 in __init__                                         │
│                                                                                                  │
│    24 │   def __init__(self, device, dtype, **kwargs):                                           │
│    25 │   │   self.device = device                                                               │
│    26 │   │   self.dtype = dtype                                                                 │
│ ❱  27 │   │   self.generator = torch.Generator(device=device)                                    │
│    28 │   │   self.pipe_dict = {                                                                 │
│    29 │   │   │   ModelType.Pix2Pix_Video: StableDiffusionInstructPix2PixPipeline,               │
│    30 │   │   │   ModelType.Text2Video: TextToVideoPipeline,                                     │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: Device type CUDA is not supported for torch.Generator() api.

**Comment by rob-hen** [comment]
Can you try if the following python code works for you:
```python
import torch
torch.Generator(device="cuda")
```

**Comment by Cubey42** [comment]
same runtime

**Comment by rob-hen** [comment]
This line of code is supposed to work, see https://pytorch.org/docs/1.13/generated/torch.Generator.html?highlight=generator#torch.Generator .

So your PyTorch installation does not work correctly. You may ask for instance at the PyTorch repository.

**Comment by habanerogossip** [comment]
I had the same issue. What fixed it for me was
`pip uninstall torch`
and then
`pip install torch==1.13.1 --index-url https://download.pytorch.org/whl/cu117`
