### ISSUE TITLE
Looking forward to the code, eager to test it out

### ISSUE THREAD

**Issue by zhanghongyong123456** [Picsart-AI-Research/Text2Video-Zero#3]
Thank you so much，When will the code be released, I think this is the best implementation related to video

**Comment by JiauZhang** [comment]
> Thank you so much，When will the code be released, I think this is the best implementation related to video

I'm trying implementation it. --> https://github.com/JiauZhang/Text2Video-Zero

**Comment by rob-hen** [comment]
Hi @zhanghongyong123456,

thank you for your interest in our code.
The code has been released.
