### ISSUE TITLE
How much VRAM will I need to run the program properly?

### ISSUE THREAD

**Issue by NeuroLord** [Picsart-AI-Research/Text2Video-Zero#4]
Will it be possible to run this text2video on 10-12 gigabyte GPUs? Perhaps with a decrease in settings but to a level where the user will receive an acceptable output result

**Comment by JiauZhang** [comment]
My implementation(https://github.com/JiauZhang/Text2Video-Zero, W.I.P) could run on GPU P100(16GB)

**Comment by rob-hen** [comment]
Hi, indeed our current code release can be run with 12 GB VRAM. We are working on reducing the memory requirement even further.

**Comment by rob-hen** [comment]
Our latest code can be tested with less than 7GB VRAM.

**Comment by sakshamjindal** [comment]
What are the setting that enable running with less than 12 GB ram. Everytime I run the code, I run into memory issues.
