### ISSUE TITLE
It seems the cross-frame attention is not implemented in the code? 

### ISSUE THREAD

**Issue by sallymmx** [Picsart-AI-Research/Text2Video-Zero#58]
Hi,
   I found that just the UNet2DConditionModel from diffusers is  directly used without any change. Where are the code of the cross-frame attention?

**Comment by ariannaliu** [comment]
Hi, same question here, have you solve this problem? Thank you!

**Comment by sallymmx** [comment]
您好，我是王蒙蒙，您的邮件我已收到，并及时回复。

**Comment by haoyan14** [comment]
Hi, I also encountered the same problem. Have you found the code related to cross-frame attention and implemented it?

**Comment by Ethan-Li123** [comment]
> 您好，我是王蒙蒙，您的邮件我已收到，并及时回复。

您好，我也遇到了相同的问题，请问是否可以转发给我一份回答，谢谢。
