### ISSUE TITLE
About the process of generating latent code

### ISSUE THREAD

**Issue by xiefan233** [Picsart-AI-Research/Text2Video-Zero#59]
Hi, this is a excellent work, but I have a few questions that I would love to hear from you.
1. Why do we need to perform DDIM Backward on latent code before warping. Is there any downside to directly warping latent code?
2. Why is DDIM Backward used in the front and DDPM Forward in the latter? Why not all DDIM, or all DDPM?

**Comment by rob-hen** [comment]
Hi @xiefan233 

If we do not apply any warping, with deterministic DDIM, we will always get the same image. With DDPM, we get. local variation (e.g. the pose of a person is changed) and with warping we can perform camera motion like translation. 

Note that in stable diffusion, early diffusion timesteps are devoted mostly to settle the scene while late diffusion timesteps are devoted mostly to improve image quality.   So it is important to apply the modification (warping and DDPM) in the right diffusion tilmestep range.
