### ISSUE TITLE
Can i use a single 1080ti gpu to run it?

### ISSUE THREAD

**Issue by hqw666666** [Picsart-AI-Research/Text2Video-Zero#6]
hello!
i am very interested in your work,but i only have a single 1080ti gpu.can i use it to get your results.
thank you!

**Comment by rob-hen** [comment]
Hi, 
we currently require 12 GB VRAM in the minimal setup, but we work on reducing the memory footprint further.

**Comment by hqw666666** [comment]
Hello!&nbsp;
Sorry&nbsp;to&nbsp;bother&nbsp;you,&nbsp;I&nbsp;am&nbsp;a&nbsp;second year&nbsp;graduate&nbsp;student&nbsp;of&nbsp;Xi'an&nbsp;University&nbsp;of&nbsp;Technology.&nbsp;Because&nbsp;I&nbsp;am&nbsp;interested&nbsp;in&nbsp;your work,&nbsp;I&nbsp;want&nbsp;to&nbsp;take&nbsp;this&nbsp;direction&nbsp;as&nbsp;a&nbsp;subject.&nbsp;After&nbsp;reading&nbsp;your《Coarse-to-Fine Reasoning for Visual Question Answering》&nbsp;paper,&nbsp;I&nbsp;am&nbsp;very&nbsp;interested&nbsp;in&nbsp;doing&nbsp;this&nbsp;direction.&nbsp;,&nbsp;and&nbsp;would&nbsp;like&nbsp;to&nbsp;explore&nbsp;further.

I&nbsp;would&nbsp;like&nbsp;to&nbsp;ask&nbsp;you:
Because it does not require training and fine-tuning.Is it possible to dig deeper？

Have&nbsp;a&nbsp;good&nbsp;day.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Picsart-AI-Research/Text2Video-Zero"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月29日(星期三) 上午6:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Picsart-AI-Research/Text2Video-Zero] Can i use a single 1080ti gpu to run it? (Issue #6)





 
Hi,
 we currently require 12 GB VRAM in the minimal setup, but we work on reducing the memory footprint further.

**Comment by hqw666666** [comment]
Hello! 
Sorry to bother you, I am a second year graduate student of Xi'an University of Technology. Because I am interested in your work, I want to take this direction as a subject. After reading your《Text-to-Image Diffusion Models are Zero-Shot Video Generators》 paper, I am very interested in doing this direction. , and would like to explore further.

I would like to ask you:
Because it does not require training and fine-tuning.Is it possible to dig deeper？

Have a good day.




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "Picsart-AI-Research/Text2Video-Zero"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月29日(星期三) 上午6:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Picsart-AI-Research/Text2Video-Zero] Can i use a single 1080ti gpu to run it? (Issue #6)





 
Hi,
 we currently require 12 GB VRAM in the minimal setup, but we work on reducing the memory footprint further.

**Comment by rob-hen** [comment]
Our latest code can be tested with less than 7GB VRAM.

**Comment by jackylee1** [comment]
> 

i have 8gb ,but i can't  see  the tab,why?
